# Sample configuration for f5-ipam-controller with infoblox provider. Infoblox configuration is mounted
# from the secret store into the controller.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: f5-ipam-controller
  name: f5-ipam-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-ipam-controller
  template:
    metadata:
      labels:
        app: f5-ipam-controller
    spec:
      containers:
        - args:
            - --orchestration=kubernetes
            - --log-level=DEBUG
            - --ipam-provider
            - infoblox
            - --infoblox-labels
            - '{"Dev" :{"cidr": "172.16.4.0/24"},"Test" :{"cidr": "172.16.5.0/24"}}'
            - --infoblox-wapi-version
            - 2.11.2
            - --infoblox-netview
            - default
            - --credentials-directory
            - /tmp/creds
          command:
            - /app/bin/f5-ipam-controller
          image: f5networks/f5-ipam-controller
          imagePullPolicy: IfNotPresent
          name: f5-ipam-controller
          volumeMounts:
            - name: infoblox-creds
              mountPath: /tmp/creds
              readOnly: true
      volumes:
      - name: infoblox-creds
        secret:
          secretName: infoblox-credentials
      serviceAccount: ipam-ctlr
      serviceAccountName: ipam-ctlr
