FROM golang as debug-builder
ENV CGO_ENABLE 0

RUN go get github.com/go-delve/delve/cmd/dlv

FROM python:3.6-slim-buster

ENV APPPATH /app

RUN mkdir -p "$APPPATH/bin" \
 && chmod -R 755 "$APPPATH" \
 && adduser --disabled-password --gecos "" ctlr

WORKDIR $APPPATH
ARG BUILD_INFO
ARG VERSION_INFO
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
    && apt-get upgrade -y \
    && apt-get remove -y git \
    # FIXME: Remove this fix once libidn is no longer vulnerable
    && apt-get remove -y libidn11 \
    && echo "{\"version\": \"${VERSION_INFO}\", \"build\": \"${BUILD_INFO}\"}" \
      > $APPPATH/VERSION_BUILD.json

COPY --from=f5-ipam-controller-builder "/go/out/bin/f5-ipam-controller" $APPPATH/bin
COPY --from=debug-builder /go/bin/dlv /app/bin

USER ctlr
EXPOSE 40000
# Run the run application in the projects bin directory.
CMD [ "/app/bin/f5-ipam-controller" ]
