# permissions for end users to view f5ipamctlrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: f5ipamctlr-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: f5-ipam-controller-operator
    app.kubernetes.io/part-of: f5-ipam-controller-operator
    app.kubernetes.io/managed-by: kustomize
  name: f5ipamctlr-viewer-role
rules:
- apiGroups:
  - fic.f5.com
  resources:
  - f5ipamctlrs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fic.f5.com
  resources:
  - f5ipamctlrs/status
  verbs:
  - get
