apiVersion: fic.f5.com/v1
kind: F5IpamCtlr
metadata:
  name: f5ipamctlr-sample
spec:
  args:
    infoblox_grid_host: IP_ADDRESS_OF_SERVER
    infoblox_labels: CIDR_Labels
    infoblox_netview: NetView
    infoblox_password: PASSWORD
    infoblox_username: USERNAME
    infoblox_wapi_version: VERSION
    ip_range: IP_RANGE_LABELS
    orchestration: kubernetes
    provider: INFOBLOX_OR_F5-IP-PROVIDER
    insecure: true
    log_level: DEBUG_OR_INFO
  image:
    pullPolicy: Always
    repo: f5-ipam-controller
    user: f5networks
    version: latest
  namespace: kube-system
  rbac:
    create: true
  serviceAccount:
    create: true